config/routes.rb
Rails.application.routes.draw do

  
  root :to => redirect('/direccions/new')
  resources :direccions
  get "/estaticas/:estaticas" => "estaticas#show"
  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :nombre,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :mensaje

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Elifaz - Contacto",
      :to => "giuseppemiro@gmail.com",
      :from => %("#{nombre}" <#{email}>)
    }
  end
end

app/models/direccion.rb
class Direccion < ActiveRecord::Base
	validates :inicial, :url =>{:message => "Introduzca una dirección válida"}
	randomized_field :generada, :length => 4
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Gracias por tu mensaje, en breve responderemos!'
    else
      flash.now[:error] = 'No se puede enviar el mensaje.'
      render :new
    end
  end
end

app/controllers/direccions_controller.rb
class DireccionsController < ApplicationController

	def index
		@direccions = Direccion.all
	end
	
	def show
		direccion = Direccion.where(:generada=>params[:id]).first
		if direccion
			direccion.clicks = direccion.clicks+1
			direccion.save
			redirect_to direccion.inicial
		else
			redirect_to :action => 'new'
		end
	end
	
	def new
		@direccion = Direccion.new
	end
	
	def parametros_direcciones
		params.require(:direccion).permit(:inicial)
	end

	def create
		@direccion = Direccion.new(parametros_direcciones)
		if @direccion.save
			render "creada"
		else
			render "new"
		end
	end
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def show
    render template: "estaticas/#{params[:estaticas]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/views/contacts/create.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/direccions/new">Elifaz</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/estaticas/acerca">Acerca de</a>
                    </li>
                    <li>
                        <a href="/contacts">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>
</nav>
<p>
<p>
<div class="container">
<header class="jumbotron hero-spacer">
<%= image_tag("logo.png", :alt => "UPTM") %>
<div>
  <% flash.each do |key, value| %>
    <div>
      <p>
      <p>
        <%= value %>
    </div>
  <% end %>
</div>
</p>
</header>

app/views/contacts/new.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/direccions/new">Elifaz</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/estaticas/acerca">Acerca de</a>
                    </li>
                    <li>
                        <a href="/contacts">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>
</nav>
<p>
<p>
<div class="container">

<header class="jumbotron hero-spacer">
<%= image_tag("logo.png", :alt => "UPTM") %>
<h2>Contacto</h2>
<div class="control-group">
  <div class="controls">
    <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :nombre, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :mensaje, :as => :text, :required => true %>
  </div>
</div>
    <div>
      </br>
      <%= f.button :submit, 'Enviar Mensaje', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</p>
</header>
	</p>

app/views/direccions/creada.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/direccions/new">Elifaz</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/estaticas/acerca">Acerca de</a>
                    </li>
                    <li>
                        <a href="/contacts">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>
</nav>
<p>
<p>
<div class="container">
<header class="jumbotron hero-spacer">
<%= image_tag("logo.png", :alt => "UPTM") %>
<h3>Tu dirección:</h3>
	<p>
	<%	cargar = Direccion.where(params[:id]).last %>
	<%= cargar.inicial %><br>
	<h3>Fue acortada a:</h3>
	<h2><a href="<%= "http://upt.co.ve/#{cargar.generada}" %>"><%= "http://upt.co.ve/#{cargar.generada}" %></a></h2>
	<br>	
	<%= link_to "Acortar otra dirección", new_direccion_path %>  
</div>
</p>
</header>

app/views/direccions/index.html.erb
<h1>Direcciones acortadas</h1>
<% @direccions.each do |direccion| %>
	<p>
	<%= link_to direccion.generada, direccion_path(:id => direccion.generada) %> => <%= direccion.inicial %> 
	<%= direccion.clicks %> 
	</p>
<% end %>

<%= link_to "Acortar otra dirección", new_direccion_path %>

app/views/direccions/new.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/direccions/new">Elifaz</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/estaticas/acerca">Acerca de</a>
                    </li>
                    <li>
                        <a href="/contacts">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>
</nav>
<p>
<p>
<div class="container">

<header class="jumbotron hero-spacer">
<%= form_for @direccion do |f| %>

<% @direccion.errors.each do |attr, msg| %>
	<%= msg %>
<% end %>
<%= image_tag("logo.png", :alt => "UPTM") %>
<h2>Acortar direccion</h2>
<div class="control-group">
  <div class="controls">
    <input id="direccion_inicial" name="direccion[inicial]" value="http://" class="input-xxlarge" type="text"><p>
     <button id="singlebutton" name="coomit" class="btn btn-primary btn-large">Acortar direccion</button>
  </div>
</div>
</p>
<% end %>

</header>
	</p>

app/views/estaticas/acerca.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/direccions/new">Elifaz</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/estaticas/acerca">Acerca de</a>
                    </li>
                    <li>
                        <a href="/contacts">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>




<div class="container-fluid">
    <header class="jumbotron hero-spacer">
    <h1>Acerca de</h1>
</header>
	<div class="row">
		<div class="col-sm-12">
		    <ul>
			<h3 class="text-info text-left">
				<li>¿En donde estoy?</li>
			</h3>
			<p class="text-left">
				Esto es el acortador de URLs <strong>Elifaz</strong> usado bajo el dominio UPT (Universidad Politécnica Territorial), con el fin de hacer mas pequeñas direcciones de interes para que así sean mas sencilas de compartir. 
			</p>
			<h3 class="text-info text-left">
			<li>¿Cómo funciona?</li>
			</h3>
			<p class="text-left">
				<strong>Elifaz</strong> toma la dirección que introduce el usuario y genera 4 caracteres únicos al azar Base36(a-z...0-9) que redirigen a la primera permanentemente. 
			</p>
			<h3 class="text-info text-left">
			<li>¿Cuanto tiempo dura la dirección generada?</li>
			</h3>
			<p class="text-left">
				<strong>Elifaz</strong> garantiza la dirección generada por un periodo de 2 mes desde la última visita a la misma.  
			</p>
			<h3 class="text-info text-left">
			<li>¿Por qué se llama <strong>Elifaz</strong>?</li>
			</h3>
			<p class="text-left">
			    El número de URLs únicas que es capaz de generar el sistema son 1.679.616 que resulta de 36<sup>4</sup> ya que es una permutación del tipo n<sup>r</sup>. Y por casualidad nos encontramos que:
			    <blockquote>
				  <p>Ada dio a luz a <strong>Elifaz</strong> para Esaú</p>
				  <footer>Genesis 36:4</cite></footer>
				</blockquote>
			</p>
			<h3 class="text-info text-left">
			<li>¿Quien hizo esto?</li>
			</h3>
			<p class="text-left">
			 <strong>Elifaz</strong> es un desarrollo libre en el que cualquiera puede colaborar a través de <a href="http://github.com/ggangix/elifaz">GITHUB</a> iniciado por <a href="http://twitter.com/ggangix">Giuseppe Gangi</a> y potenciado
			 por la <a href="https://twitter.com/tilpea">Comunidad de Aprendizaje de Tecnologías Libres de Información</a> del programa de estudios abiertos de la <a href="http://uptm.edu.ve/">UPTM</a> 
			</p>
			</ul>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Acortador de URLs - UPT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>